feat: dev overlay
dot-base/error-handler pull request #4
Opened 2022-04-12 15:59 UTC by rti

closes #3

2022-04-12 16:11 UTC, rti commented
https://github.com/dot-base/dot-base/issues/71

2022-04-13 09:25 UTC, friedow requested changes

2022-04-13 09:25 UTC, friedow commented on .vscode/launch.json
> +            "url": "https://dotbase.local:8080/error/404/",
The url `https://dotbase.local:8080/error/404/` returns `Secure Connection Failed` which I can't skip while `https://dotbase.local/error/404/` returns a `Bad Gateway`. This might be a deployment error in the traefik config of the dot.base stack but needs to be fixed anyway.

2022-04-14 15:14 UTC, rti commented on .vscode/launch.json
> +            "url": "https://dotbase.local:8080/error/404/",
there is no https on 8080, only http

2022-04-25 12:39 UTC, friedow approved these changes

2022-04-25 12:49 UTC, merged